import {
  Bitमंथन1,
  Bitमंथन2,
  Bitमंथन3,
  Bitमंथन4,
  Bitमंथन5,
  Bitमंथन6,
  Bitमंथन7,
  Bitमंथन8,
  Bitमंथन9,
  Bitमंथन10,
  Bitमंथन11,
  Bitमंथन12,
} from "../../assets/EventAssets/Bitमंथन";

import {
  Ideathon1,
  Ideathon2,
  Ideathon3,
  Ideathon4,
  Ideathon5,
  Ideathon6,
  Ideathon7,
  Ideathon8,
  Ideathon9,
  Ideathon10,
  Ideathon11,
  Ideathon12,
} from "../../assets/EventAssets/Ideathon24";

import {
  CryptoCarnival1,
  CryptoCarnival2,
  CryptoCarnival3,
  CryptoCarnival4,
  CryptoCarnival5,
  CryptoCarnival6,
  CryptoCarnival7,
  CryptoCarnival8,
  CryptoCarnival9,
  CryptoCarnival10,
  CryptoCarnival11,
  CryptoCarnival12,
} from "../../assets/EventAssets/CryptoCarnival";

const EventData = () => [
  {
    id: 1,
    name: "Bitमंथन",
    date: "28th Aug 2023",
    images: [
      Bitमंथन1,
      Bitमंथन2,
      Bitमंथन3,
      Bitमंथन4,
      Bitमंथन5,
      Bitमंथन6,
      Bitमंथन7,
      Bitमंथन8,
      Bitमंथन9,
      Bitमंथन10,
      Bitमंथन11,
      Bitमंथन12,
    ],
  },
  {
    id: 2,
    name: "Ideathon'24",
    date: "23rd Feb 2024",
    images: [
      Ideathon1,
      Ideathon2,
      Ideathon3,
      Ideathon4,
      Ideathon5,
      Ideathon6,
      Ideathon7,
      Ideathon8,
      Ideathon9,
      Ideathon10,
      Ideathon11,
      Ideathon12,
    ],
  },
  {
    id: 3,
    name: "CryptoCarnival",
    date: "10th May 2024",
    images: [
      CryptoCarnival1,
      CryptoCarnival2,
      CryptoCarnival3,
      CryptoCarnival4,
      CryptoCarnival5,
      CryptoCarnival6,
      CryptoCarnival7,
      CryptoCarnival8,
      CryptoCarnival9,
      CryptoCarnival10,
      CryptoCarnival11,
      CryptoCarnival12,
    ],
  },
];

export default EventData;
